---
title: "6. Comparing Means"
output: html_document
---

### This chapter describes statistical tests to use for comparing means.

#### These tests include:

  - T-test  
  - Wilcoxon test  
  - ANOVA test and  
  - Kruskal-Wallis test  

***

### 1. How this chapter is organized?

  - Comparing one-sample mean to a standard known mean:
    + One-Sample T-test ($\color{red}{parametric}$)
    + One-Sample Wilcoxon Test ($\color{blue}{non-parametric}$)
  - Comparing the means of two independent groups:
    + Unpaired Two Samples T-test ($\color{red}{parametric}$)
    + Unpaired Two-Samples Wilcoxon Test ($\color{blue}{non-parametric}$)
  - Comparing the means of paired samples:
    + Paired Samples T-test ($\color{red}{parametric}$)
    + Paired Samples Wilcoxon Test ($\color{blue}{non-parametric}$)
  - Comparing the means of more than two groups
    + Analysis of variance (ANOVA, $\color{red}{parametric}$):
      + One-Way ANOVA Test in R
      + Two-Way ANOVA Test in R
      + MANOVA Test in R: Multivariate Analysis of Variance
    + Kruskal-Wallis Test in R ($\color{blue}{non-parametric}$ alternative to one-way ANOVA)

***

### 2. Comparing one-sample mean to a standard known mean

  - One-sample T-test ( $\color{red}{parametric}$ )
  
    + brief outlines:
      + What is one-sample t-test?
      + Research questions and statistical hypotheses
      + Formula of one-sample t-test
      + Visualize your data and compute one-sample t-test in R
        + R function to compute one-sample t-test
        + Visualize your data using box plots
        + Preliminary test to check one-sample t-test assumptions
        + Compute one-sample t-test
        + Interpretation of the result
</p>

  - One-sample Wilcoxon test ( $\color{blue}{non-parametric}$ )
  
    + brief outlines:
      + What’s one-sample Wilcoxon signed rank test?
      + Research questions and statistical hypotheses
      + Visualize your data and compute one-sample Wilcoxon test in R
        + R function to compute one-sample Wilcoxon test
        + Visualize your data using box plots
        + Compute one-sample Wilcoxon test

***

### 3. Comparing the means of two independent groups

  - Unpaired two samples t-test ( $\color{red}{parametric}$ )

    + brief outlines:
      + What is unpaired two-samples t-test?
      + Research questions and statistical hypotheses
      + Formula of unpaired two-samples t-test
      + Visualize your data and compute unpaired two-samples t-test in R
        + R function to compute unpaired two-samples t-test
        + Visualize your data using box plots
        + Preliminary test to check independent t-test assumptions
        + Compute unpaired two-samples t-test
        + Interpretation of the result
</p>

  - Unpaired two-samples Wilcoxon test ( $\color{blue}{non-parametric}$ )

    + brief outlines:
      + R function to compute Wilcoxon test
      + Visualize your data using box plots
      + Compute unpaired two-samples Wilcoxon test

***

### 4. Comparing the means of paired samples

  - Paired samples t-test ( $\color{red}{parametric}$ )
  - Paired samples Wilcoxon test ( $\color{blue}{non-parametric}$ )

***

### 5. Comparing the means of more than two groups

  - One-way ANOVA test ( $\color{red}{parametric}$ )
  
    + An extension of independent two-samples t-test for comparing means 
      in a situation where there are more than two groups.
      
    + brief outlines:
      + What is one-way ANOVA test?
      + Assumptions of ANOVA test
      + How one-way ANOVA test works?
      + Visualize your data and compute one-way ANOVA in R
      + Visualize your data
      + Compute one-way ANOVA test
      + Interpret the result of one-way ANOVA tests
      + Multiple pairwise-comparison between the means of groups
        + Tukey multiple pairewise-comparisons
        + Multiple comparisons using multcomp package
        + Pairwise t-test
      + Check ANOVA assumptions: test validity?
        + Check the homogeneity of variance assumption
        + Relaxing the homogeneity of variance assumption
        + Check the normality assumption
      + Non-parametric alternative to one-way ANOVA test
</p>

  - Two-Way ANOVA test ( $\color{red}{parametric}$ )
  
    + brief outlines:
      + What is two-way ANOVA test?
      + Two-way ANOVA test hypotheses
      + Assumptions of two-way ANOVA test
      + Compute two-way ANOVA test in R: balanced designs
      + Visualize your data
      + Compute two-way ANOVA test
      + Interpret the results
      + Compute some summary statistics
      + Multiple pairwise-comparison between the means of groups:
        + Tukey multiple pairewise-comparisons
        + Multiple comparisons using multcomp package
        + Pairwise t-test
      + Check ANOVA assumptions: test validity?
        + Check the homogeneity of variance assumption
        + Check the normality assumption
      + Compute two-way ANOVA test in R for unbalanced designs
<p/>

  - MANOVA test: Multivariate analysis of variance ( $\color{red}{parametric}$ )

    + brief outlines:
      + What is MANOVA test?
      + Assumptions of MANOVA
      + Interpretation of MANOVA
      + Compute MANOVA in R
</p>

  - Kruskal-Wallis test ( $\color{blue}{non-parametric}$ )

    + brief outlines:
      + What is Kruskal-Wallis test?
      + Visualize your data and compute Kruskal-Wallis test in R
        + Visualize the data using box plots
        + Compute Kruskal-Wallis test
        + Multiple pairwise-comparison between groups